version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:864899837235:task-definition/user9-new-task-definition:1"
        LoadBalancerInfo:
          ContainerName: "user9-container"
          ContainerPort: 80
